/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSearchRouteImport } from './routes/_authed/search'
import { Route as ApiOpdsIndexRouteImport } from './routes/api/opds/index'
import { Route as ApiOpdsSearchRouteImport } from './routes/api/opds/search'
import { Route as ApiOpdsRecentRouteImport } from './routes/api/opds/recent'
import { Route as ApiOpdsAllRouteImport } from './routes/api/opds/all'
import { Route as ApiKosyncHealthcheckRouteImport } from './routes/api/kosync/healthcheck'
import { Route as ApiCoversBookIdRouteImport } from './routes/api/covers/$bookId'
import { Route as ApiBooksFileIdRouteImport } from './routes/api/books/$fileId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedShelvesShelfIdRouteImport } from './routes/_authed/shelves.$shelfId'
import { Route as AuthedSettingsUsersRouteImport } from './routes/_authed/settings/users'
import { Route as AuthedSettingsSyncRouteImport } from './routes/_authed/settings/sync'
import { Route as AuthedSettingsScanningRouteImport } from './routes/_authed/settings/scanning'
import { Route as AuthedSettingsLibrariesRouteImport } from './routes/_authed/settings/libraries'
import { Route as AuthedSettingsJobsRouteImport } from './routes/_authed/settings/jobs'
import { Route as AuthedSettingsGeneralRouteImport } from './routes/_authed/settings/general'
import { Route as AuthedSeriesSeriesIdRouteImport } from './routes/_authed/series.$seriesId'
import { Route as AuthedReadingListsListIdRouteImport } from './routes/_authed/reading-lists.$listId'
import { Route as AuthedLibrariesLibraryIdRouteImport } from './routes/_authed/libraries.$libraryId'
import { Route as AuthedCollectionsCollectionIdRouteImport } from './routes/_authed/collections.$collectionId'
import { Route as AuthedBooksBookIdRouteImport } from './routes/_authed/books.$bookId'
import { Route as AuthedAuthorsAuthorIdRouteImport } from './routes/_authed/authors.$authorId'
import { Route as ApiOpdsSearchXmlRouteImport } from './routes/api/opds/search.xml'
import { Route as ApiOpdsLibrariesLibraryIdRouteImport } from './routes/api/opds/libraries.$libraryId'
import { Route as ApiKosyncUsersCreateRouteImport } from './routes/api/kosync/users.create'
import { Route as ApiKosyncUsersAuthRouteImport } from './routes/api/kosync/users.auth'
import { Route as ApiKosyncSyncsProgressRouteImport } from './routes/api/kosync/syncs.progress'
import { Route as AuthedReadBookIdFileIdRouteImport } from './routes/_authed/read.$bookId.$fileId'
import { Route as ApiOpdsPseBookIdPageNumberRouteImport } from './routes/api/opds/pse.$bookId.$pageNumber'
import { Route as ApiKoboTokenV1InitializationRouteImport } from './routes/api/kobo/$token/v1/initialization'
import { Route as ApiKoboTokenV1LibrarySyncRouteImport } from './routes/api/kobo/$token/v1/library.sync'
import { Route as ApiKoboTokenV1LibraryBookIdStateRouteImport } from './routes/api/kobo/$token/v1/library.$bookId.state'
import { Route as ApiKoboTokenV1LibraryBookIdDownloadRouteImport } from './routes/api/kobo/$token/v1/library.$bookId.download'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSearchRoute = AuthedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiOpdsIndexRoute = ApiOpdsIndexRouteImport.update({
  id: '/api/opds/',
  path: '/api/opds/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpdsSearchRoute = ApiOpdsSearchRouteImport.update({
  id: '/api/opds/search',
  path: '/api/opds/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpdsRecentRoute = ApiOpdsRecentRouteImport.update({
  id: '/api/opds/recent',
  path: '/api/opds/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpdsAllRoute = ApiOpdsAllRouteImport.update({
  id: '/api/opds/all',
  path: '/api/opds/all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKosyncHealthcheckRoute = ApiKosyncHealthcheckRouteImport.update({
  id: '/api/kosync/healthcheck',
  path: '/api/kosync/healthcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoversBookIdRoute = ApiCoversBookIdRouteImport.update({
  id: '/api/covers/$bookId',
  path: '/api/covers/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBooksFileIdRoute = ApiBooksFileIdRouteImport.update({
  id: '/api/books/$fileId',
  path: '/api/books/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedShelvesShelfIdRoute = AuthedShelvesShelfIdRouteImport.update({
  id: '/shelves/$shelfId',
  path: '/shelves/$shelfId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsUsersRoute = AuthedSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsSyncRoute = AuthedSettingsSyncRouteImport.update({
  id: '/settings/sync',
  path: '/settings/sync',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsScanningRoute = AuthedSettingsScanningRouteImport.update({
  id: '/settings/scanning',
  path: '/settings/scanning',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsLibrariesRoute = AuthedSettingsLibrariesRouteImport.update({
  id: '/settings/libraries',
  path: '/settings/libraries',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsJobsRoute = AuthedSettingsJobsRouteImport.update({
  id: '/settings/jobs',
  path: '/settings/jobs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsGeneralRoute = AuthedSettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSeriesSeriesIdRoute = AuthedSeriesSeriesIdRouteImport.update({
  id: '/series/$seriesId',
  path: '/series/$seriesId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReadingListsListIdRoute =
  AuthedReadingListsListIdRouteImport.update({
    id: '/reading-lists/$listId',
    path: '/reading-lists/$listId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedLibrariesLibraryIdRoute =
  AuthedLibrariesLibraryIdRouteImport.update({
    id: '/libraries/$libraryId',
    path: '/libraries/$libraryId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedCollectionsCollectionIdRoute =
  AuthedCollectionsCollectionIdRouteImport.update({
    id: '/collections/$collectionId',
    path: '/collections/$collectionId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedBooksBookIdRoute = AuthedBooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuthorsAuthorIdRoute = AuthedAuthorsAuthorIdRouteImport.update({
  id: '/authors/$authorId',
  path: '/authors/$authorId',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiOpdsSearchXmlRoute = ApiOpdsSearchXmlRouteImport.update({
  id: '/xml',
  path: '/xml',
  getParentRoute: () => ApiOpdsSearchRoute,
} as any)
const ApiOpdsLibrariesLibraryIdRoute =
  ApiOpdsLibrariesLibraryIdRouteImport.update({
    id: '/api/opds/libraries/$libraryId',
    path: '/api/opds/libraries/$libraryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiKosyncUsersCreateRoute = ApiKosyncUsersCreateRouteImport.update({
  id: '/api/kosync/users/create',
  path: '/api/kosync/users/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKosyncUsersAuthRoute = ApiKosyncUsersAuthRouteImport.update({
  id: '/api/kosync/users/auth',
  path: '/api/kosync/users/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKosyncSyncsProgressRoute = ApiKosyncSyncsProgressRouteImport.update({
  id: '/api/kosync/syncs/progress',
  path: '/api/kosync/syncs/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedReadBookIdFileIdRoute = AuthedReadBookIdFileIdRouteImport.update({
  id: '/read/$bookId/$fileId',
  path: '/read/$bookId/$fileId',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiOpdsPseBookIdPageNumberRoute =
  ApiOpdsPseBookIdPageNumberRouteImport.update({
    id: '/api/opds/pse/$bookId/$pageNumber',
    path: '/api/opds/pse/$bookId/$pageNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiKoboTokenV1InitializationRoute =
  ApiKoboTokenV1InitializationRouteImport.update({
    id: '/api/kobo/$token/v1/initialization',
    path: '/api/kobo/$token/v1/initialization',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiKoboTokenV1LibrarySyncRoute =
  ApiKoboTokenV1LibrarySyncRouteImport.update({
    id: '/api/kobo/$token/v1/library/sync',
    path: '/api/kobo/$token/v1/library/sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiKoboTokenV1LibraryBookIdStateRoute =
  ApiKoboTokenV1LibraryBookIdStateRouteImport.update({
    id: '/api/kobo/$token/v1/library/$bookId/state',
    path: '/api/kobo/$token/v1/library/$bookId/state',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiKoboTokenV1LibraryBookIdDownloadRoute =
  ApiKoboTokenV1LibraryBookIdDownloadRouteImport.update({
    id: '/api/kobo/$token/v1/library/$bookId/download',
    path: '/api/kobo/$token/v1/library/$bookId/download',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof AuthedSearchRoute
  '/authors/$authorId': typeof AuthedAuthorsAuthorIdRoute
  '/books/$bookId': typeof AuthedBooksBookIdRoute
  '/collections/$collectionId': typeof AuthedCollectionsCollectionIdRoute
  '/libraries/$libraryId': typeof AuthedLibrariesLibraryIdRoute
  '/reading-lists/$listId': typeof AuthedReadingListsListIdRoute
  '/series/$seriesId': typeof AuthedSeriesSeriesIdRoute
  '/settings/general': typeof AuthedSettingsGeneralRoute
  '/settings/jobs': typeof AuthedSettingsJobsRoute
  '/settings/libraries': typeof AuthedSettingsLibrariesRoute
  '/settings/scanning': typeof AuthedSettingsScanningRoute
  '/settings/sync': typeof AuthedSettingsSyncRoute
  '/settings/users': typeof AuthedSettingsUsersRoute
  '/shelves/$shelfId': typeof AuthedShelvesShelfIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/books/$fileId': typeof ApiBooksFileIdRoute
  '/api/covers/$bookId': typeof ApiCoversBookIdRoute
  '/api/kosync/healthcheck': typeof ApiKosyncHealthcheckRoute
  '/api/opds/all': typeof ApiOpdsAllRoute
  '/api/opds/recent': typeof ApiOpdsRecentRoute
  '/api/opds/search': typeof ApiOpdsSearchRouteWithChildren
  '/api/opds/': typeof ApiOpdsIndexRoute
  '/read/$bookId/$fileId': typeof AuthedReadBookIdFileIdRoute
  '/api/kosync/syncs/progress': typeof ApiKosyncSyncsProgressRoute
  '/api/kosync/users/auth': typeof ApiKosyncUsersAuthRoute
  '/api/kosync/users/create': typeof ApiKosyncUsersCreateRoute
  '/api/opds/libraries/$libraryId': typeof ApiOpdsLibrariesLibraryIdRoute
  '/api/opds/search/xml': typeof ApiOpdsSearchXmlRoute
  '/api/kobo/$token/v1/initialization': typeof ApiKoboTokenV1InitializationRoute
  '/api/opds/pse/$bookId/$pageNumber': typeof ApiOpdsPseBookIdPageNumberRoute
  '/api/kobo/$token/v1/library/sync': typeof ApiKoboTokenV1LibrarySyncRoute
  '/api/kobo/$token/v1/library/$bookId/download': typeof ApiKoboTokenV1LibraryBookIdDownloadRoute
  '/api/kobo/$token/v1/library/$bookId/state': typeof ApiKoboTokenV1LibraryBookIdStateRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof AuthedSearchRoute
  '/': typeof AuthedIndexRoute
  '/authors/$authorId': typeof AuthedAuthorsAuthorIdRoute
  '/books/$bookId': typeof AuthedBooksBookIdRoute
  '/collections/$collectionId': typeof AuthedCollectionsCollectionIdRoute
  '/libraries/$libraryId': typeof AuthedLibrariesLibraryIdRoute
  '/reading-lists/$listId': typeof AuthedReadingListsListIdRoute
  '/series/$seriesId': typeof AuthedSeriesSeriesIdRoute
  '/settings/general': typeof AuthedSettingsGeneralRoute
  '/settings/jobs': typeof AuthedSettingsJobsRoute
  '/settings/libraries': typeof AuthedSettingsLibrariesRoute
  '/settings/scanning': typeof AuthedSettingsScanningRoute
  '/settings/sync': typeof AuthedSettingsSyncRoute
  '/settings/users': typeof AuthedSettingsUsersRoute
  '/shelves/$shelfId': typeof AuthedShelvesShelfIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/books/$fileId': typeof ApiBooksFileIdRoute
  '/api/covers/$bookId': typeof ApiCoversBookIdRoute
  '/api/kosync/healthcheck': typeof ApiKosyncHealthcheckRoute
  '/api/opds/all': typeof ApiOpdsAllRoute
  '/api/opds/recent': typeof ApiOpdsRecentRoute
  '/api/opds/search': typeof ApiOpdsSearchRouteWithChildren
  '/api/opds': typeof ApiOpdsIndexRoute
  '/read/$bookId/$fileId': typeof AuthedReadBookIdFileIdRoute
  '/api/kosync/syncs/progress': typeof ApiKosyncSyncsProgressRoute
  '/api/kosync/users/auth': typeof ApiKosyncUsersAuthRoute
  '/api/kosync/users/create': typeof ApiKosyncUsersCreateRoute
  '/api/opds/libraries/$libraryId': typeof ApiOpdsLibrariesLibraryIdRoute
  '/api/opds/search/xml': typeof ApiOpdsSearchXmlRoute
  '/api/kobo/$token/v1/initialization': typeof ApiKoboTokenV1InitializationRoute
  '/api/opds/pse/$bookId/$pageNumber': typeof ApiOpdsPseBookIdPageNumberRoute
  '/api/kobo/$token/v1/library/sync': typeof ApiKoboTokenV1LibrarySyncRoute
  '/api/kobo/$token/v1/library/$bookId/download': typeof ApiKoboTokenV1LibraryBookIdDownloadRoute
  '/api/kobo/$token/v1/library/$bookId/state': typeof ApiKoboTokenV1LibraryBookIdStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authed/search': typeof AuthedSearchRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/authors/$authorId': typeof AuthedAuthorsAuthorIdRoute
  '/_authed/books/$bookId': typeof AuthedBooksBookIdRoute
  '/_authed/collections/$collectionId': typeof AuthedCollectionsCollectionIdRoute
  '/_authed/libraries/$libraryId': typeof AuthedLibrariesLibraryIdRoute
  '/_authed/reading-lists/$listId': typeof AuthedReadingListsListIdRoute
  '/_authed/series/$seriesId': typeof AuthedSeriesSeriesIdRoute
  '/_authed/settings/general': typeof AuthedSettingsGeneralRoute
  '/_authed/settings/jobs': typeof AuthedSettingsJobsRoute
  '/_authed/settings/libraries': typeof AuthedSettingsLibrariesRoute
  '/_authed/settings/scanning': typeof AuthedSettingsScanningRoute
  '/_authed/settings/sync': typeof AuthedSettingsSyncRoute
  '/_authed/settings/users': typeof AuthedSettingsUsersRoute
  '/_authed/shelves/$shelfId': typeof AuthedShelvesShelfIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/books/$fileId': typeof ApiBooksFileIdRoute
  '/api/covers/$bookId': typeof ApiCoversBookIdRoute
  '/api/kosync/healthcheck': typeof ApiKosyncHealthcheckRoute
  '/api/opds/all': typeof ApiOpdsAllRoute
  '/api/opds/recent': typeof ApiOpdsRecentRoute
  '/api/opds/search': typeof ApiOpdsSearchRouteWithChildren
  '/api/opds/': typeof ApiOpdsIndexRoute
  '/_authed/read/$bookId/$fileId': typeof AuthedReadBookIdFileIdRoute
  '/api/kosync/syncs/progress': typeof ApiKosyncSyncsProgressRoute
  '/api/kosync/users/auth': typeof ApiKosyncUsersAuthRoute
  '/api/kosync/users/create': typeof ApiKosyncUsersCreateRoute
  '/api/opds/libraries/$libraryId': typeof ApiOpdsLibrariesLibraryIdRoute
  '/api/opds/search/xml': typeof ApiOpdsSearchXmlRoute
  '/api/kobo/$token/v1/initialization': typeof ApiKoboTokenV1InitializationRoute
  '/api/opds/pse/$bookId/$pageNumber': typeof ApiOpdsPseBookIdPageNumberRoute
  '/api/kobo/$token/v1/library/sync': typeof ApiKoboTokenV1LibrarySyncRoute
  '/api/kobo/$token/v1/library/$bookId/download': typeof ApiKoboTokenV1LibraryBookIdDownloadRoute
  '/api/kobo/$token/v1/library/$bookId/state': typeof ApiKoboTokenV1LibraryBookIdStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/search'
    | '/authors/$authorId'
    | '/books/$bookId'
    | '/collections/$collectionId'
    | '/libraries/$libraryId'
    | '/reading-lists/$listId'
    | '/series/$seriesId'
    | '/settings/general'
    | '/settings/jobs'
    | '/settings/libraries'
    | '/settings/scanning'
    | '/settings/sync'
    | '/settings/users'
    | '/shelves/$shelfId'
    | '/api/auth/$'
    | '/api/books/$fileId'
    | '/api/covers/$bookId'
    | '/api/kosync/healthcheck'
    | '/api/opds/all'
    | '/api/opds/recent'
    | '/api/opds/search'
    | '/api/opds/'
    | '/read/$bookId/$fileId'
    | '/api/kosync/syncs/progress'
    | '/api/kosync/users/auth'
    | '/api/kosync/users/create'
    | '/api/opds/libraries/$libraryId'
    | '/api/opds/search/xml'
    | '/api/kobo/$token/v1/initialization'
    | '/api/opds/pse/$bookId/$pageNumber'
    | '/api/kobo/$token/v1/library/sync'
    | '/api/kobo/$token/v1/library/$bookId/download'
    | '/api/kobo/$token/v1/library/$bookId/state'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/search'
    | '/'
    | '/authors/$authorId'
    | '/books/$bookId'
    | '/collections/$collectionId'
    | '/libraries/$libraryId'
    | '/reading-lists/$listId'
    | '/series/$seriesId'
    | '/settings/general'
    | '/settings/jobs'
    | '/settings/libraries'
    | '/settings/scanning'
    | '/settings/sync'
    | '/settings/users'
    | '/shelves/$shelfId'
    | '/api/auth/$'
    | '/api/books/$fileId'
    | '/api/covers/$bookId'
    | '/api/kosync/healthcheck'
    | '/api/opds/all'
    | '/api/opds/recent'
    | '/api/opds/search'
    | '/api/opds'
    | '/read/$bookId/$fileId'
    | '/api/kosync/syncs/progress'
    | '/api/kosync/users/auth'
    | '/api/kosync/users/create'
    | '/api/opds/libraries/$libraryId'
    | '/api/opds/search/xml'
    | '/api/kobo/$token/v1/initialization'
    | '/api/opds/pse/$bookId/$pageNumber'
    | '/api/kobo/$token/v1/library/sync'
    | '/api/kobo/$token/v1/library/$bookId/download'
    | '/api/kobo/$token/v1/library/$bookId/state'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/register'
    | '/_authed/search'
    | '/_authed/'
    | '/_authed/authors/$authorId'
    | '/_authed/books/$bookId'
    | '/_authed/collections/$collectionId'
    | '/_authed/libraries/$libraryId'
    | '/_authed/reading-lists/$listId'
    | '/_authed/series/$seriesId'
    | '/_authed/settings/general'
    | '/_authed/settings/jobs'
    | '/_authed/settings/libraries'
    | '/_authed/settings/scanning'
    | '/_authed/settings/sync'
    | '/_authed/settings/users'
    | '/_authed/shelves/$shelfId'
    | '/api/auth/$'
    | '/api/books/$fileId'
    | '/api/covers/$bookId'
    | '/api/kosync/healthcheck'
    | '/api/opds/all'
    | '/api/opds/recent'
    | '/api/opds/search'
    | '/api/opds/'
    | '/_authed/read/$bookId/$fileId'
    | '/api/kosync/syncs/progress'
    | '/api/kosync/users/auth'
    | '/api/kosync/users/create'
    | '/api/opds/libraries/$libraryId'
    | '/api/opds/search/xml'
    | '/api/kobo/$token/v1/initialization'
    | '/api/opds/pse/$bookId/$pageNumber'
    | '/api/kobo/$token/v1/library/sync'
    | '/api/kobo/$token/v1/library/$bookId/download'
    | '/api/kobo/$token/v1/library/$bookId/state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBooksFileIdRoute: typeof ApiBooksFileIdRoute
  ApiCoversBookIdRoute: typeof ApiCoversBookIdRoute
  ApiKosyncHealthcheckRoute: typeof ApiKosyncHealthcheckRoute
  ApiOpdsAllRoute: typeof ApiOpdsAllRoute
  ApiOpdsRecentRoute: typeof ApiOpdsRecentRoute
  ApiOpdsSearchRoute: typeof ApiOpdsSearchRouteWithChildren
  ApiOpdsIndexRoute: typeof ApiOpdsIndexRoute
  ApiKosyncSyncsProgressRoute: typeof ApiKosyncSyncsProgressRoute
  ApiKosyncUsersAuthRoute: typeof ApiKosyncUsersAuthRoute
  ApiKosyncUsersCreateRoute: typeof ApiKosyncUsersCreateRoute
  ApiOpdsLibrariesLibraryIdRoute: typeof ApiOpdsLibrariesLibraryIdRoute
  ApiKoboTokenV1InitializationRoute: typeof ApiKoboTokenV1InitializationRoute
  ApiOpdsPseBookIdPageNumberRoute: typeof ApiOpdsPseBookIdPageNumberRoute
  ApiKoboTokenV1LibrarySyncRoute: typeof ApiKoboTokenV1LibrarySyncRoute
  ApiKoboTokenV1LibraryBookIdDownloadRoute: typeof ApiKoboTokenV1LibraryBookIdDownloadRoute
  ApiKoboTokenV1LibraryBookIdStateRoute: typeof ApiKoboTokenV1LibraryBookIdStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/search': {
      id: '/_authed/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthedSearchRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/opds/': {
      id: '/api/opds/'
      path: '/api/opds'
      fullPath: '/api/opds/'
      preLoaderRoute: typeof ApiOpdsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/opds/search': {
      id: '/api/opds/search'
      path: '/api/opds/search'
      fullPath: '/api/opds/search'
      preLoaderRoute: typeof ApiOpdsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/opds/recent': {
      id: '/api/opds/recent'
      path: '/api/opds/recent'
      fullPath: '/api/opds/recent'
      preLoaderRoute: typeof ApiOpdsRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/opds/all': {
      id: '/api/opds/all'
      path: '/api/opds/all'
      fullPath: '/api/opds/all'
      preLoaderRoute: typeof ApiOpdsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kosync/healthcheck': {
      id: '/api/kosync/healthcheck'
      path: '/api/kosync/healthcheck'
      fullPath: '/api/kosync/healthcheck'
      preLoaderRoute: typeof ApiKosyncHealthcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/covers/$bookId': {
      id: '/api/covers/$bookId'
      path: '/api/covers/$bookId'
      fullPath: '/api/covers/$bookId'
      preLoaderRoute: typeof ApiCoversBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/books/$fileId': {
      id: '/api/books/$fileId'
      path: '/api/books/$fileId'
      fullPath: '/api/books/$fileId'
      preLoaderRoute: typeof ApiBooksFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/shelves/$shelfId': {
      id: '/_authed/shelves/$shelfId'
      path: '/shelves/$shelfId'
      fullPath: '/shelves/$shelfId'
      preLoaderRoute: typeof AuthedShelvesShelfIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/users': {
      id: '/_authed/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthedSettingsUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/sync': {
      id: '/_authed/settings/sync'
      path: '/settings/sync'
      fullPath: '/settings/sync'
      preLoaderRoute: typeof AuthedSettingsSyncRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/scanning': {
      id: '/_authed/settings/scanning'
      path: '/settings/scanning'
      fullPath: '/settings/scanning'
      preLoaderRoute: typeof AuthedSettingsScanningRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/libraries': {
      id: '/_authed/settings/libraries'
      path: '/settings/libraries'
      fullPath: '/settings/libraries'
      preLoaderRoute: typeof AuthedSettingsLibrariesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/jobs': {
      id: '/_authed/settings/jobs'
      path: '/settings/jobs'
      fullPath: '/settings/jobs'
      preLoaderRoute: typeof AuthedSettingsJobsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/general': {
      id: '/_authed/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthedSettingsGeneralRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/series/$seriesId': {
      id: '/_authed/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof AuthedSeriesSeriesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reading-lists/$listId': {
      id: '/_authed/reading-lists/$listId'
      path: '/reading-lists/$listId'
      fullPath: '/reading-lists/$listId'
      preLoaderRoute: typeof AuthedReadingListsListIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/libraries/$libraryId': {
      id: '/_authed/libraries/$libraryId'
      path: '/libraries/$libraryId'
      fullPath: '/libraries/$libraryId'
      preLoaderRoute: typeof AuthedLibrariesLibraryIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/collections/$collectionId': {
      id: '/_authed/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof AuthedCollectionsCollectionIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/books/$bookId': {
      id: '/_authed/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof AuthedBooksBookIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/authors/$authorId': {
      id: '/_authed/authors/$authorId'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId'
      preLoaderRoute: typeof AuthedAuthorsAuthorIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/opds/search/xml': {
      id: '/api/opds/search/xml'
      path: '/xml'
      fullPath: '/api/opds/search/xml'
      preLoaderRoute: typeof ApiOpdsSearchXmlRouteImport
      parentRoute: typeof ApiOpdsSearchRoute
    }
    '/api/opds/libraries/$libraryId': {
      id: '/api/opds/libraries/$libraryId'
      path: '/api/opds/libraries/$libraryId'
      fullPath: '/api/opds/libraries/$libraryId'
      preLoaderRoute: typeof ApiOpdsLibrariesLibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kosync/users/create': {
      id: '/api/kosync/users/create'
      path: '/api/kosync/users/create'
      fullPath: '/api/kosync/users/create'
      preLoaderRoute: typeof ApiKosyncUsersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kosync/users/auth': {
      id: '/api/kosync/users/auth'
      path: '/api/kosync/users/auth'
      fullPath: '/api/kosync/users/auth'
      preLoaderRoute: typeof ApiKosyncUsersAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kosync/syncs/progress': {
      id: '/api/kosync/syncs/progress'
      path: '/api/kosync/syncs/progress'
      fullPath: '/api/kosync/syncs/progress'
      preLoaderRoute: typeof ApiKosyncSyncsProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/read/$bookId/$fileId': {
      id: '/_authed/read/$bookId/$fileId'
      path: '/read/$bookId/$fileId'
      fullPath: '/read/$bookId/$fileId'
      preLoaderRoute: typeof AuthedReadBookIdFileIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/opds/pse/$bookId/$pageNumber': {
      id: '/api/opds/pse/$bookId/$pageNumber'
      path: '/api/opds/pse/$bookId/$pageNumber'
      fullPath: '/api/opds/pse/$bookId/$pageNumber'
      preLoaderRoute: typeof ApiOpdsPseBookIdPageNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kobo/$token/v1/initialization': {
      id: '/api/kobo/$token/v1/initialization'
      path: '/api/kobo/$token/v1/initialization'
      fullPath: '/api/kobo/$token/v1/initialization'
      preLoaderRoute: typeof ApiKoboTokenV1InitializationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kobo/$token/v1/library/sync': {
      id: '/api/kobo/$token/v1/library/sync'
      path: '/api/kobo/$token/v1/library/sync'
      fullPath: '/api/kobo/$token/v1/library/sync'
      preLoaderRoute: typeof ApiKoboTokenV1LibrarySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kobo/$token/v1/library/$bookId/state': {
      id: '/api/kobo/$token/v1/library/$bookId/state'
      path: '/api/kobo/$token/v1/library/$bookId/state'
      fullPath: '/api/kobo/$token/v1/library/$bookId/state'
      preLoaderRoute: typeof ApiKoboTokenV1LibraryBookIdStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kobo/$token/v1/library/$bookId/download': {
      id: '/api/kobo/$token/v1/library/$bookId/download'
      path: '/api/kobo/$token/v1/library/$bookId/download'
      fullPath: '/api/kobo/$token/v1/library/$bookId/download'
      preLoaderRoute: typeof ApiKoboTokenV1LibraryBookIdDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedSearchRoute: typeof AuthedSearchRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAuthorsAuthorIdRoute: typeof AuthedAuthorsAuthorIdRoute
  AuthedBooksBookIdRoute: typeof AuthedBooksBookIdRoute
  AuthedCollectionsCollectionIdRoute: typeof AuthedCollectionsCollectionIdRoute
  AuthedLibrariesLibraryIdRoute: typeof AuthedLibrariesLibraryIdRoute
  AuthedReadingListsListIdRoute: typeof AuthedReadingListsListIdRoute
  AuthedSeriesSeriesIdRoute: typeof AuthedSeriesSeriesIdRoute
  AuthedSettingsGeneralRoute: typeof AuthedSettingsGeneralRoute
  AuthedSettingsJobsRoute: typeof AuthedSettingsJobsRoute
  AuthedSettingsLibrariesRoute: typeof AuthedSettingsLibrariesRoute
  AuthedSettingsScanningRoute: typeof AuthedSettingsScanningRoute
  AuthedSettingsSyncRoute: typeof AuthedSettingsSyncRoute
  AuthedSettingsUsersRoute: typeof AuthedSettingsUsersRoute
  AuthedShelvesShelfIdRoute: typeof AuthedShelvesShelfIdRoute
  AuthedReadBookIdFileIdRoute: typeof AuthedReadBookIdFileIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSearchRoute: AuthedSearchRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAuthorsAuthorIdRoute: AuthedAuthorsAuthorIdRoute,
  AuthedBooksBookIdRoute: AuthedBooksBookIdRoute,
  AuthedCollectionsCollectionIdRoute: AuthedCollectionsCollectionIdRoute,
  AuthedLibrariesLibraryIdRoute: AuthedLibrariesLibraryIdRoute,
  AuthedReadingListsListIdRoute: AuthedReadingListsListIdRoute,
  AuthedSeriesSeriesIdRoute: AuthedSeriesSeriesIdRoute,
  AuthedSettingsGeneralRoute: AuthedSettingsGeneralRoute,
  AuthedSettingsJobsRoute: AuthedSettingsJobsRoute,
  AuthedSettingsLibrariesRoute: AuthedSettingsLibrariesRoute,
  AuthedSettingsScanningRoute: AuthedSettingsScanningRoute,
  AuthedSettingsSyncRoute: AuthedSettingsSyncRoute,
  AuthedSettingsUsersRoute: AuthedSettingsUsersRoute,
  AuthedShelvesShelfIdRoute: AuthedShelvesShelfIdRoute,
  AuthedReadBookIdFileIdRoute: AuthedReadBookIdFileIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface ApiOpdsSearchRouteChildren {
  ApiOpdsSearchXmlRoute: typeof ApiOpdsSearchXmlRoute
}

const ApiOpdsSearchRouteChildren: ApiOpdsSearchRouteChildren = {
  ApiOpdsSearchXmlRoute: ApiOpdsSearchXmlRoute,
}

const ApiOpdsSearchRouteWithChildren = ApiOpdsSearchRoute._addFileChildren(
  ApiOpdsSearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBooksFileIdRoute: ApiBooksFileIdRoute,
  ApiCoversBookIdRoute: ApiCoversBookIdRoute,
  ApiKosyncHealthcheckRoute: ApiKosyncHealthcheckRoute,
  ApiOpdsAllRoute: ApiOpdsAllRoute,
  ApiOpdsRecentRoute: ApiOpdsRecentRoute,
  ApiOpdsSearchRoute: ApiOpdsSearchRouteWithChildren,
  ApiOpdsIndexRoute: ApiOpdsIndexRoute,
  ApiKosyncSyncsProgressRoute: ApiKosyncSyncsProgressRoute,
  ApiKosyncUsersAuthRoute: ApiKosyncUsersAuthRoute,
  ApiKosyncUsersCreateRoute: ApiKosyncUsersCreateRoute,
  ApiOpdsLibrariesLibraryIdRoute: ApiOpdsLibrariesLibraryIdRoute,
  ApiKoboTokenV1InitializationRoute: ApiKoboTokenV1InitializationRoute,
  ApiOpdsPseBookIdPageNumberRoute: ApiOpdsPseBookIdPageNumberRoute,
  ApiKoboTokenV1LibrarySyncRoute: ApiKoboTokenV1LibrarySyncRoute,
  ApiKoboTokenV1LibraryBookIdDownloadRoute:
    ApiKoboTokenV1LibraryBookIdDownloadRoute,
  ApiKoboTokenV1LibraryBookIdStateRoute: ApiKoboTokenV1LibraryBookIdStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
